# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: trusty
sudo: false  

addons:
  apt:
    packages:
    #- python-matplotlib 
    #- python-numpy 
    #- python-scipy 
    - python-tk
    - python-lxml
    - python-tornado
    - libhdf5-7
    - python-tables

language: python
python: 2.7

virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=NetPyNE 

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - pip install numpy scipy # Why is this needed? Scipy doesn't seem to get installed correctly on trusty with addons above...
    - pip install tables # Ditto
    - pip install matplotlib # This is more because Matplotlib v2.x is required...
    
script:
    - omv all -V
    - omv list
    - pwd
    - ls -al NeuroML2
    - cd NeuroML2/scaling
    - if [[ ${OMV_ENGINE} == "jNeuroML_NetPyNE" ]]; then python LEMS_Balanced_hdf5_netpyne.py ; fi
    
    
    

