# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

sudo: false  

language: python
python: 2.7

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=jNeuroML_NetPyNE
    # - OMV_ENGINE=NetPyNE Gives errors due to matplotlib

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    
script:
    - omv all -V
    - omv list-engines
    - pwd
    - ls -al NeuroML2
    - cd NeuroML2
    - python LEMS_2007One_netpyne.py
    
    
    

