# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

sudo: false  

addons:
  apt:
    packages:
    - python-matplotlib 
    - python-tk
    #- python-numpy 
    - python-scipy 
    - python-lxml
    #- python-sympy

language: python
python: 2.7

virtualenv:
    system_site_packages: true

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=jNeuroML_NetPyNE
    # - OMV_ENGINE=NetPyNE Gives errors due to matplotlib

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - pip install git+https://github.com/NeuralEnsemble/libNeuroML.git@development
    - pip install git+https://github.com/NeuroML/pyNeuroML
    
script:
    - omv all -V
    - omv list-engines
    - pwd
    - ls -al NeuroML2
    - cd NeuroML2
    - if [[ ${OMV_ENGINE} == "jNeuroML_NetPyNE" ]]; then python LEMS_2007One_netpyne.py ; fi
    
    
    

