# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial
sudo: false  

addons:
  apt:
    packages:
    - python-tk
    - python-lxml
    - python-tornado
    - python-tables

language: python
python: 
    - 2.7
    - 3.7

env:
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_validate
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=NetPyNE 

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation
    - pip install numpy scipy # Why is this needed? Scipy doesn't seem to get installed correctly with addons above...
    - pip install tables # Ditto
    - pip install matplotlib
    - pip install future pandas matplotlib-scalebar bokeh
    #- pip install neuron # to test - need to find out where nrn installed...
    
script:
    - omv list-engines -V
    - omv all -V
    - pwd
    - ls -al NeuroML2
    - cd NeuroML2/scaling
    - if [[ ${OMV_ENGINE} == "jNeuroML_NetPyNE" ]]; then python LEMS_Balanced_hdf5_netpyne.py ; fi
    - cd ../..
    - if [[ ${OMV_ENGINE} == "jNeuroML_NetPyNE" ]]; then ./regenerateAndTest.sh ; fi
    - omv list-engines -V
    
    
    
    

