TITLE Mod file for component: Component(id=gj1 type=gapJunction)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.6.1
         org.neuroml.model   v1.6.1
         jLEMS               v0.10.1

ENDCOMMENT

NEURON {
    POINT_PROCESS gj1
    RANGE weight                            : property
    RANGE conductance                       : parameter
    
    RANGE i                                 : exposure
    
    
    NONSPECIFIC_CURRENT i 
    RANGE vpeer: derived variable; RANGE, not POINTER for Parallel NEURON...
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    weight = 1
    conductance = 1.0E-5 (uS)
}

ASSIGNED {
    ? Standard Assigned variables with baseSynapse
    v (mV)
    celsius (degC)
    temperature (K)
    
    vpeer (mV)                             : derived variable
    
    i : no units???                        : derived variable
    
}

STATE {
    
}

INITIAL {
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
}

BREAKPOINT {
    
    rates()
    
}

PROCEDURE rates() {
    
    ? DerivedVariable is based on path: peer/v, on: Component(id=gj1 type=gapJunction), from peer; null
    ? Derived variable: vpeer; its value will be set by a pointer...
    
    i = -1 * weight  *  conductance  * (vpeer - v) ? evaluable
    
     
    
}

