TITLE Mod file for component: Component(id=IF_curr_alpha_E_net type=IF_curr_alpha)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.0
         org.neuroml.model   v1.5.0
         jLEMS               v0.9.8.7

ENDCOMMENT

NEURON {
    POINT_PROCESS IF_curr_alpha_E_net
    
    
    NONSPECIFIC_CURRENT i                    : To ensure v of section follows vI
    RANGE tau_refrac                        : parameter
    RANGE v_thresh                          : parameter
    RANGE tau_m                             : parameter
    RANGE v_rest                            : parameter
    RANGE v_reset                           : parameter
    RANGE cm                                : parameter
    RANGE i_offset                          : parameter
    RANGE tau_syn_E                         : parameter
    RANGE tau_syn_I                         : parameter
    RANGE v_init                            : parameter
    RANGE MSEC                              : parameter
    RANGE MVOLT                             : parameter
    RANGE NFARAD                            : parameter
    
    RANGE iSyn                              : exposure
    
    RANGE copy_v                           : copy of v on section
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (S) = (siemens)
    
}

PARAMETER {
    
    tau_refrac = 2 
    v_thresh = 20 
    tau_m = 20 
    v_rest = 0 
    v_reset = 0 
    cm = 0.001 
    i_offset = 0 
    tau_syn_E = 0.1 
    tau_syn_I = 0.1 
    v_init = -10 
    MSEC = 1 (ms)
    MVOLT = 1 (mV)
    NFARAD = 9.999999E-4 (microfarads)
}

ASSIGNED {
    v (mV)
    i (mA/cm2)
    
    copy_v (mV)
    
    
    iSyn (nA)                              : derived variable
    
    rate_v (mV/ms)
    
}

STATE {
    regime_refractory (1)
    regime_integrating (1)
    vI (nA) 
    lastSpikeTime (ms) 
    
}

INITIAL {
    rates()
    rates() ? To ensure correct initialisation.
    
    regime_refractory = 0
    
    regime_integrating = 1
    
    net_send(0, 1) : go to NET_RECEIVE block, flag 1, for initial state
    
}

BREAKPOINT {
    
    rates()
    
    copy_v = v
    i = vI * cm
}

NET_RECEIVE(flag) {
    
    if (flag == 1) { : Setting watch condition for regime_refractory
        WATCH (t >  lastSpikeTime  + (  tau_refrac  *  MSEC  )) 5002
    }
    
    if (regime_refractory == 1 && flag == 5002) { : Setting actions for regime_refractory
    
            : State assignments
    
            : Change regime flags
            regime_refractory = 0
            regime_integrating = 1
    
            : OnEntry to Regime: integrating (initial = true)
    }
    
    if (flag == 1) { : Setting watch condition for regime_integrating
        WATCH (v >  v_thresh  *  MVOLT) 5003
    }
    
    if (regime_integrating == 1 && flag == 5003) { : Setting actions for regime_integrating
    
            : State assignments
    
            : Change regime flags
            regime_integrating = 0
            regime_refractory = 1
    
            : OnEntry to Regime: refractory (initial = false)
    
            lastSpikeTime = t
    
            v = v_reset  *  MVOLT
    }
    if (flag == 1) { : Set initial states
    
        v = v_init  *  MVOLT
    }
    
}

PROCEDURE rates() {
    
    ? DerivedVariable is based on path: synapses[*]/i, on: Component(id=IF_curr_alpha_E_net type=IF_curr_alpha), from synapses; null
    iSyn = 0 ? Was: synapses[*]_i but insertion of currents from external attachments not yet supported ? path based
    
    rate_v = 0 + regime_refractory * (10000000 * (v_reset * MVOLT - v)) + regime_integrating * ((  MVOLT   * ((  i_offset  /  cm  ) +  ((  v_rest   - (v/  MVOLT  )) /   tau_m  ))/  MSEC  ) + (  iSyn   / (  cm   *   NFARAD  ))) ? Note units of all quantities used here need to be consistent!
    
    vI = -1 * rate_v
     
    
}

