'''
NetPyNE simulator compliant export for:

Components:
    null (Type: property)
    IF_curr_alpha_E_net (Type: IF_curr_alpha:  tau_refrac=2.0 (dimensionless) v_thresh=20.0 (dimensionless) tau_m=20.0 (dimensionless) v_rest=0.0 (dimensionless) v_reset=0.0 (dimensionless) cm=0.001 (dimensionless) i_offset=0.0 (dimensionless) tau_syn_E=0.1 (dimensionless) tau_syn_I=0.1 (dimensionless) v_init=-10.0 (dimensionless) MSEC=0.001 (SI time) MVOLT=0.001 (SI voltage) NFARAD=1.0E-9 (SI capacitance))
    syn__expoisson__TO__E_net (Type: alphaCurrSynapse:  tau_syn=0.1 (dimensionless) MSEC=0.001 (SI time) MVOLT=0.001 (SI voltage) NAMP=1.0E-9 (SI current))
    SpikeSourcePoisson_expoisson (Type: SpikeSourcePoisson:  start=0.0 (SI time) duration=1.0E7 (SI time) rate=200.0 (SI per_time) end=1.0E7 (SI time) LONG_TIME=3.6E12 (SI time))
    Spikers (Type: networkWithTemperature:  temperature=305.15 (SI temperature))
    Sim_Spikers (Type: Simulation:  length=1.0 (SI time) step=2.5E-5 (SI time))


    This NetPyNE file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.5.0
         org.neuroml.model   v1.5.0
         jLEMS               v0.9.8.7

'''
# Main NetPyNE script for: Spikers

# See https://github.com/Neurosim-lab/netpyne

from netpyne import specs  # import netpyne specs module
from netpyne import sim    # import netpyne sim module

from neuron import h


###############################################################################
# NETWORK PARAMETERS
###############################################################################

nml2_file_name = 'Spikers.net.nml'

###############################################################################
# SIMULATION PARAMETERS
###############################################################################

simConfig = specs.SimConfig()   # object of class SimConfig to store the simulation configuration

# Simulation parameters
simConfig.duration = simConfig.tstop = 1000.0 # Duration of the simulation, in ms
simConfig.dt = 0.024999999 # Internal integration timestep to use
simConfig.randseed = 1 # Random seed to use
simConfig.createNEURONObj = 1  # create HOC objects when instantiating network
simConfig.createPyStruct = 1  # create Python structure (simulator-independent) when instantiating network
simConfig.verbose = True  # show detailed messages 
simConfig.hParams['celsius'] = (305.15 - 273.15)

# Recording 
simConfig.recordCells = ['all']  
simConfig.recordTraces = {}

# For saving to file: E_net_v.dat (ref: OF_E_net_v)
# Column: E_net_0_IF_curr_alpha_E_net_v: Pop: E_net; cell: 0; segment id: $oc.segment_id; segment name: soma; Neuron loc: soma(0.5); value: v (v)
simConfig.recordTraces['OF_E_net_v_E_net_0_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'popLabel':'E_net','cellLabel':0}}


simConfig.plotCells = ['all']


simConfig.recordStim = True  # record spikes of cell stims
simConfig.recordStep = simConfig.dt # Step size in ms to save data (eg. V traces, LFP, etc)



# Analysis and plotting 
simConfig.plotRaster = True # Whether or not to plot a raster
simConfig.plotLFPSpectrum = False # plot power spectral density
simConfig.maxspikestoplot = 3e8 # Maximum number of spikes to plot
simConfig.plotConn = False # whether to plot conn matrix
simConfig.plotWeightChanges = False # whether to plot weight changes (shown in conn matrix)
#simConfig.plot3dArch = True # plot 3d architecture

# Saving
simConfig.filename = 'Spikers.txt'  # Set file output name
simConfig.saveFileStep = simConfig.dt # step size in ms to save data to disk
# simConfig.saveDat = True # save to dat file


###############################################################################
# IMPORT & RUN
###############################################################################

print("Running a NetPyNE based simulation for %sms (dt: %sms) at %s degC"%(simConfig.duration, simConfig.dt, h.celsius))

gids = sim.importNeuroML2SimulateAnalyze(nml2_file_name,simConfig)

print("Finished simulation")


###############################################################################
#   Saving data (this ensures the data gets saved in the format/files 
#   as specified in the LEMS <Simulation> element)
###############################################################################


if sim.rank==0: 
    print("Saving to file: E_net_v.dat (ref: OF_E_net_v)")

 
    # Column: t
    col_OF_E_net_v_t = [i*simConfig.dt for i in range(int(simConfig.duration/simConfig.dt))]

    # Column: E_net_0_IF_curr_alpha_E_net_v: Pop: E_net; cell: 0; segment id: $oc.segment_id; segment name: soma; value: v
    col_OF_E_net_v_E_net_0_IF_curr_alpha_E_net_v = sim.allSimData['OF_E_net_v_E_net_0_soma_v']['cell_%s'%gids['E_net'][0]]

    dat_file_OF_E_net_v = open('E_net_v.dat', 'w')
    for i in range(len(col_OF_E_net_v_t)):
        dat_file_OF_E_net_v.write( '%s\t'%(col_OF_E_net_v_t[i]/1000) +  '%s\t'%(col_OF_E_net_v_E_net_0_IF_curr_alpha_E_net_v[i]/1000.0) +  '\n')
    dat_file_OF_E_net_v.close()


    print("Saved all data.")
