TITLE Mod file for component: Component(id=Ca_conc type=fixedFactorConcentrationModel)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.9.1
         org.neuroml.model   v1.9.1
         jLEMS               v0.10.8

ENDCOMMENT

NEURON {
    SUFFIX Ca_conc
    USEION ca READ cai, cao, ica WRITE cai VALENCE 2
    RANGE cai
    RANGE cao
    GLOBAL initialConcentration
    GLOBAL initialExtConcentration
    RANGE restingConc                       : parameter
    RANGE decayConstant                     : parameter
    RANGE rho                               : parameter
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    
}

PARAMETER {
    surfaceArea (cm2)
    iCa (nA)
    initialConcentration (mM)
    initialExtConcentration (mM)
    
    restingConc = 0 (mM)                   : was: 0.0 (concentration)
    decayConstant = 100 (ms)               : was: 0.1 (time)
    rho = 9.54315E-5 (umol / cm / nA / ms) : was: 9543.150099999999 (rho_factor)
}

ASSIGNED {
    cai (mM)
    cao (mM)
    ica (mA/cm2)
    i__Ca_conc (mA/cm2)
    diam (um)                               : Added to facilitate access to section's diam
    area (um2)                              : Added to facilitate access to section's area
    rate_concentration (mM/ms)
    
}

STATE {
    concentration (mM) : dimension: concentration
    extConcentration (mM) : dimension: concentration
    
}

INITIAL {
    initialConcentration = cai
    initialExtConcentration = cao
    rates()
    rates() ? To ensure correct initialisation.
    
    concentration = initialConcentration
    
    extConcentration = initialExtConcentration
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    if (concentration  < 0) {
        concentration = 0 ? standard OnCondition
    }
    
    
}

DERIVATIVE states {
    rates()
    concentration' = rate_concentration
    cai = concentration 
    
}

PROCEDURE rates() {
    
    surfaceArea = (1e-08)*(area)   : surfaceArea has units (cm2), area (built in to NEURON) is in um^2...
    
    iCa = (1e6) * (-1 * ica * surfaceArea) :   iCa has units (nA) ; ica (built in to NEURON) has units (mA/cm2)...
    
    rate_concentration = (iCa/surfaceArea) *  rho  - ((  concentration   -   restingConc  ) /   decayConstant  ) ? Note units of all quantities used here need to be consistent!
    
     
    
}

