TITLE Mod file for component: Component(id=GABA_syn_inh type=expTwoSynapse)

COMMENT

    This NEURON file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.10.1
         org.neuroml.model   v1.10.1
         jLEMS               v0.11.1

ENDCOMMENT

NEURON {
    POINT_PROCESS GABA_syn_inh
    RANGE tauRise                           : parameter
    RANGE tauDecay                          : parameter
    RANGE peakTime                          : parameter
    RANGE waveformFactor                    : parameter
    RANGE gbase                             : parameter
    RANGE erev                              : parameter
    RANGE g                                 : exposure
    RANGE i                                 : exposure
    
    
    NONSPECIFIC_CURRENT i 
    
}

UNITS {
    
    (nA) = (nanoamp)
    (uA) = (microamp)
    (mA) = (milliamp)
    (A) = (amp)
    (mV) = (millivolt)
    (mS) = (millisiemens)
    (uS) = (microsiemens)
    (nF) = (nanofarad)
    (molar) = (1/liter)
    (kHz) = (kilohertz)
    (mM) = (millimolar)
    (um) = (micrometer)
    (umol) = (micromole)
    (pC) = (picocoulomb)
    (S) = (siemens)
    
}

PARAMETER {
    
    tauRise = 3 (ms)                       : was: 0.003 (time)
    tauDecay = 8 (ms)                      : was: 0.008 (time)
    peakTime = 4.7079806 (ms)              : was: 0.004707980414456286 (time)
    waveformFactor = 2.8820481             : was: 2.8820480821773082 (none)
    gbase = 0 (uS)                         : was: 0.0 (conductance)
    erev = -80 (mV)                        : was: -0.08 (voltage)
}

ASSIGNED {
    ? Standard Assigned variables with baseSynapse
    v (mV)
    celsius (degC)
    temperature (K)
    g (uS)                                  : derived variable
    i (nA)                                  : derived variable
    rate_A (/ms)
    rate_B (/ms)
    
}

STATE {
    A  : dimension: none
    B  : dimension: none
    
}

INITIAL {
    temperature = celsius + 273.15
    
    rates()
    rates() ? To ensure correct initialisation.
    
    A = 0
    
    B = 0
    
}

BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    
}

NET_RECEIVE(weight) {
    
    : paramMappings . : {GABA_syn_inh={A=A, B=B, tauRise=tauRise, tauDecay=tauDecay, peakTime=peakTime, waveformFactor=waveformFactor, gbase=gbase, erev=erev, g=g, i=i}, GABA_syn_inh_notes={}}
    : state_discontinuity(A, A  + (weight *   waveformFactor  )) : From GABA_syn_inh
    A = A  + (weight *   waveformFactor  ) : From GABA_syn_inh
    
    : paramMappings . : {GABA_syn_inh={A=A, B=B, tauRise=tauRise, tauDecay=tauDecay, peakTime=peakTime, waveformFactor=waveformFactor, gbase=gbase, erev=erev, g=g, i=i}, GABA_syn_inh_notes={}}
    : state_discontinuity(B, B  + (weight *   waveformFactor  )) : From GABA_syn_inh
    B = B  + (weight *   waveformFactor  ) : From GABA_syn_inh
    
}

DERIVATIVE states {
    rates()
    A' = rate_A 
    B' = rate_B 
    
}

PROCEDURE rates() {
    
    g = gbase  * (  B   -   A  ) ? evaluable
    i = -1 * g  * (  erev   - v) ? evaluable
    rate_A = -  A   /  tauRise ? Note units of all quantities used here need to be consistent!
    rate_B = -  B   /  tauDecay ? Note units of all quantities used here need to be consistent!
    
     
    
}

