'''
NETPYNE simulator compliant export for:

Components:
    null (Type: notes)
    AMPA_syn (Type: expTwoSynapse:  tauRise=0.003 (SI time) tauDecay=0.0031 (SI time) peakTime=0.0030494535225381453 (SI time) waveformFactor=82.9038820519792 (dimensionless) gbase=3.0E-8 (SI conductance) erev=0.0 (SI voltage))
    null (Type: notes)
    AMPA_syn_inh (Type: expTwoSynapse:  tauRise=0.003 (SI time) tauDecay=0.0031 (SI time) peakTime=0.0030494535225381453 (SI time) waveformFactor=82.9038820519792 (dimensionless) gbase=1.5E-10 (SI conductance) erev=0.0 (SI voltage))
    null (Type: notes)
    Ca_conc (Type: fixedFactorConcentrationModel:  restingConc=0.0 (SI concentration) decayConstant=0.1 (SI time) rho=9543.150099999999 (SI rho_factor))
    null (Type: notes)
    Ca_pyr (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    GABA_syn (Type: expTwoSynapse:  tauRise=0.005 (SI time) tauDecay=0.012 (SI time) peakTime=0.007504017748747713 (SI time) waveformFactor=3.203779841251092 (dimensionless) gbase=6.0E-10 (SI conductance) erev=-0.08 (SI voltage))
    null (Type: notes)
    GABA_syn_inh (Type: expTwoSynapse:  tauRise=0.003 (SI time) tauDecay=0.008 (SI time) peakTime=0.004707980414456286 (SI time) waveformFactor=2.882048082177309 (dimensionless) gbase=0.0 (SI conductance) erev=-0.08 (SI voltage))
    null (Type: notes)
    Kahp_pyr (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    Kdr_bask (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    Kdr_pyr (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    LeakConductance_bask (Type: ionChannelPassive:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    LeakConductance_pyr (Type: ionChannelPassive:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    Na_bask (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    null (Type: notes)
    Na_pyr (Type: ionChannelHH:  conductance=1.0E-11 (SI conductance))
    bask (Type: cell)
    pyr_4_sym (Type: cell)
    null (Type: notes)
    BackgroundRandomIClamps (Type: pulseGenerator:  delay=0.0 (SI time) duration=100.0 (SI time) amplitude=6.0E-10 (SI current))
    network_ACnet2 (Type: networkWithTemperature:  temperature=279.45 (SI temperature))
    sim1 (Type: Simulation:  length=0.5 (SI time) step=1.0E-5 (SI time))


    This NETPYNE file has been generated by org.neuroml.export (see https://github.com/NeuroML/org.neuroml.export)
         org.neuroml.export  v1.10.1
         org.neuroml.model   v1.10.1
         jLEMS               v0.11.1

'''
# Main NetPyNE script for: network_ACnet2

# See https://github.com/Neurosim-lab/netpyne

from netpyne import specs  # import netpyne specs module
from netpyne import sim    # import netpyne sim module
from netpyne import __version__ as version

from neuron import h

import sys
import time
import datetime

class NetPyNESimulation():

    def __init__(self, tstop=500.0, dt=0.01, seed=123456789, save_json=False, abs_tol=None):

        self.setup_start = time.time()
        
        self.report_file = open('simulator.props','w')
        self.report_file.write('# Report of running simulation with NetPyNE v%s\n'%version)
        self.report_file.write('Simulator=NetPyNE\n')
        self.report_file.write('SimulatorVersion=%s\n'%version)
        self.report_file.write('SimulationFile=%s\n'%__file__)
        self.report_file.write('PythonVersion=%s\n'%sys.version.replace('\n',' '))
        self.report_file.write('NeuronVersion=%s\n'%h.nrnversion())
        self.report_file.write('NeuroMLExportVersion=1.10.1\n')
        self.report_file.close()
        

        ###############################################################################
        # NETWORK PARAMETERS
        ###############################################################################

        self.nml2_file_name = 'MediumNet.net.nml'

        ###############################################################################
        # SIMULATION PARAMETERS
        ###############################################################################

        self.simConfig = specs.SimConfig()   # object of class SimConfig to store the simulation configuration

        # Simulation parameters
        self.simConfig.duration = self.simConfig.tstop = tstop # Duration of the simulation, in ms
        self.simConfig.dt = dt # Internal integration timestep to use

        # cvode
        if abs_tol is not None:
            self.simConfig.cvode_active = True
            self.simConfig.cvode_atol = abs_tol
        else:
            self.simConfig.cvode_active = False

        # Seeds for randomizers (connectivity, input stimulation and cell locations)
        # Note: locations and connections should be fully specified by the structure of the NeuroML,
        # so seeds for conn & loc shouldn't affect networks structure/behaviour
        self.simConfig.seeds = {'conn': 0, 'stim': 123456789, 'loc': 0}

        self.simConfig.createNEURONObj = 1  # create HOC objects when instantiating network
        self.simConfig.createPyStruct = 1  # create Python structure (simulator-independent) when instantiating network
        self.simConfig.verbose = False  # show detailed messages
        
        self.simConfig.hParams['celsius'] = (279.45 - 273.15)
        
        # Recording
        self.simConfig.recordCells = ['all']
        self.simConfig.recordTraces = {}
        self.simConfig.saveCellSecs=False
        self.simConfig.saveCellConns=False
        self.simConfig.gatherOnlySimData=True

                # For saving to file: baskets_12_0.0.dat (ref: baskets_12_v_0_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 0; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_0_0_OF_baskets_12_0_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':0}}
                        
                # For saving to file: baskets_12_1.0.dat (ref: baskets_12_v_1_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 1; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_1_0_OF_baskets_12_1_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':1}}
                        
                # For saving to file: baskets_12_2.0.dat (ref: baskets_12_v_2_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 2; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_2_0_OF_baskets_12_2_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':2}}
                        
                # For saving to file: baskets_12_3.0.dat (ref: baskets_12_v_3_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 3; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_3_0_OF_baskets_12_3_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':3}}
                        
                # For saving to file: baskets_12_4.0.dat (ref: baskets_12_v_4_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 4; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_4_0_OF_baskets_12_4_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':4}}
                        
                # For saving to file: baskets_12_5.0.dat (ref: baskets_12_v_5_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 5; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_5_0_OF_baskets_12_5_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':5}}
                        
                # For saving to file: baskets_12_6.0.dat (ref: baskets_12_v_6_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 6; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_6_0_OF_baskets_12_6_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':6}}
                        
                # For saving to file: baskets_12_7.0.dat (ref: baskets_12_v_7_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 7; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_7_0_OF_baskets_12_7_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':7}}
                        
                # For saving to file: baskets_12_8.0.dat (ref: baskets_12_v_8_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 8; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_8_0_OF_baskets_12_8_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':8}}
                        
                # For saving to file: baskets_12_9.0.dat (ref: baskets_12_v_9_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 9; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_9_0_OF_baskets_12_9_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':9}}
                        
                # For saving to file: baskets_12_10.0.dat (ref: baskets_12_v_10_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 10; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_10_0_OF_baskets_12_10_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':10}}
                        
                # For saving to file: baskets_12_11.0.dat (ref: baskets_12_v_11_0_OF)
                                
        # Column: v: Pop: baskets_12; cell: 11; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['baskets_12_v_11_0_OF_baskets_12_11_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'baskets_12','cellLabel':11}}
                        
                # For saving to file: pyramidals_48_0.0.dat (ref: pyramidals_48_v_0_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 0; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_0_0_OF_pyramidals_48_0_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':0}}
                        
                # For saving to file: pyramidals_48_1.0.dat (ref: pyramidals_48_v_1_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 1; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_1_0_OF_pyramidals_48_1_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':1}}
                        
                # For saving to file: pyramidals_48_2.0.dat (ref: pyramidals_48_v_2_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 2; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_2_0_OF_pyramidals_48_2_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':2}}
                        
                # For saving to file: pyramidals_48_3.0.dat (ref: pyramidals_48_v_3_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 3; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_3_0_OF_pyramidals_48_3_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':3}}
                        
                # For saving to file: pyramidals_48_4.0.dat (ref: pyramidals_48_v_4_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 4; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_4_0_OF_pyramidals_48_4_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':4}}
                        
                # For saving to file: pyramidals_48_5.0.dat (ref: pyramidals_48_v_5_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 5; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_5_0_OF_pyramidals_48_5_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':5}}
                        
                # For saving to file: pyramidals_48_6.0.dat (ref: pyramidals_48_v_6_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 6; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_6_0_OF_pyramidals_48_6_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':6}}
                        
                # For saving to file: pyramidals_48_7.0.dat (ref: pyramidals_48_v_7_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 7; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_7_0_OF_pyramidals_48_7_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':7}}
                        
                # For saving to file: pyramidals_48_8.0.dat (ref: pyramidals_48_v_8_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 8; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_8_0_OF_pyramidals_48_8_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':8}}
                        
                # For saving to file: pyramidals_48_9.0.dat (ref: pyramidals_48_v_9_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 9; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_9_0_OF_pyramidals_48_9_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':9}}
                        
                # For saving to file: pyramidals_48_10.0.dat (ref: pyramidals_48_v_10_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 10; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_10_0_OF_pyramidals_48_10_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':10}}
                        
                # For saving to file: pyramidals_48_11.0.dat (ref: pyramidals_48_v_11_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 11; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_11_0_OF_pyramidals_48_11_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':11}}
                        
                # For saving to file: pyramidals_48_12.0.dat (ref: pyramidals_48_v_12_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 12; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_12_0_OF_pyramidals_48_12_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':12}}
                        
                # For saving to file: pyramidals_48_13.0.dat (ref: pyramidals_48_v_13_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 13; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_13_0_OF_pyramidals_48_13_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':13}}
                        
                # For saving to file: pyramidals_48_14.0.dat (ref: pyramidals_48_v_14_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 14; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_14_0_OF_pyramidals_48_14_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':14}}
                        
                # For saving to file: pyramidals_48_15.0.dat (ref: pyramidals_48_v_15_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 15; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_15_0_OF_pyramidals_48_15_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':15}}
                        
                # For saving to file: pyramidals_48_16.0.dat (ref: pyramidals_48_v_16_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 16; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_16_0_OF_pyramidals_48_16_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':16}}
                        
                # For saving to file: pyramidals_48_17.0.dat (ref: pyramidals_48_v_17_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 17; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_17_0_OF_pyramidals_48_17_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':17}}
                        
                # For saving to file: pyramidals_48_18.0.dat (ref: pyramidals_48_v_18_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 18; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_18_0_OF_pyramidals_48_18_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':18}}
                        
                # For saving to file: pyramidals_48_19.0.dat (ref: pyramidals_48_v_19_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 19; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_19_0_OF_pyramidals_48_19_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':19}}
                        
                # For saving to file: pyramidals_48_20.0.dat (ref: pyramidals_48_v_20_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 20; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_20_0_OF_pyramidals_48_20_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':20}}
                        
                # For saving to file: pyramidals_48_21.0.dat (ref: pyramidals_48_v_21_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 21; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_21_0_OF_pyramidals_48_21_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':21}}
                        
                # For saving to file: pyramidals_48_22.0.dat (ref: pyramidals_48_v_22_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 22; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_22_0_OF_pyramidals_48_22_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':22}}
                        
                # For saving to file: pyramidals_48_23.0.dat (ref: pyramidals_48_v_23_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 23; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_23_0_OF_pyramidals_48_23_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':23}}
                        
                # For saving to file: pyramidals_48_24.0.dat (ref: pyramidals_48_v_24_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 24; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_24_0_OF_pyramidals_48_24_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':24}}
                        
                # For saving to file: pyramidals_48_25.0.dat (ref: pyramidals_48_v_25_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 25; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_25_0_OF_pyramidals_48_25_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':25}}
                        
                # For saving to file: pyramidals_48_26.0.dat (ref: pyramidals_48_v_26_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 26; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_26_0_OF_pyramidals_48_26_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':26}}
                        
                # For saving to file: pyramidals_48_27.0.dat (ref: pyramidals_48_v_27_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 27; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_27_0_OF_pyramidals_48_27_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':27}}
                        
                # For saving to file: pyramidals_48_28.0.dat (ref: pyramidals_48_v_28_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 28; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_28_0_OF_pyramidals_48_28_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':28}}
                        
                # For saving to file: pyramidals_48_29.0.dat (ref: pyramidals_48_v_29_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 29; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_29_0_OF_pyramidals_48_29_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':29}}
                        
                # For saving to file: pyramidals_48_30.0.dat (ref: pyramidals_48_v_30_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 30; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_30_0_OF_pyramidals_48_30_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':30}}
                        
                # For saving to file: pyramidals_48_31.0.dat (ref: pyramidals_48_v_31_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 31; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_31_0_OF_pyramidals_48_31_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':31}}
                        
                # For saving to file: pyramidals_48_32.0.dat (ref: pyramidals_48_v_32_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 32; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_32_0_OF_pyramidals_48_32_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':32}}
                        
                # For saving to file: pyramidals_48_33.0.dat (ref: pyramidals_48_v_33_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 33; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_33_0_OF_pyramidals_48_33_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':33}}
                        
                # For saving to file: pyramidals_48_34.0.dat (ref: pyramidals_48_v_34_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 34; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_34_0_OF_pyramidals_48_34_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':34}}
                        
                # For saving to file: pyramidals_48_35.0.dat (ref: pyramidals_48_v_35_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 35; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_35_0_OF_pyramidals_48_35_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':35}}
                        
                # For saving to file: pyramidals_48_36.0.dat (ref: pyramidals_48_v_36_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 36; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_36_0_OF_pyramidals_48_36_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':36}}
                        
                # For saving to file: pyramidals_48_37.0.dat (ref: pyramidals_48_v_37_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 37; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_37_0_OF_pyramidals_48_37_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':37}}
                        
                # For saving to file: pyramidals_48_38.0.dat (ref: pyramidals_48_v_38_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 38; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_38_0_OF_pyramidals_48_38_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':38}}
                        
                # For saving to file: pyramidals_48_39.0.dat (ref: pyramidals_48_v_39_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 39; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_39_0_OF_pyramidals_48_39_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':39}}
                        
                # For saving to file: pyramidals_48_40.0.dat (ref: pyramidals_48_v_40_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 40; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_40_0_OF_pyramidals_48_40_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':40}}
                        
                # For saving to file: pyramidals_48_41.0.dat (ref: pyramidals_48_v_41_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 41; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_41_0_OF_pyramidals_48_41_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':41}}
                        
                # For saving to file: pyramidals_48_42.0.dat (ref: pyramidals_48_v_42_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 42; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_42_0_OF_pyramidals_48_42_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':42}}
                        
                # For saving to file: pyramidals_48_43.0.dat (ref: pyramidals_48_v_43_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 43; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_43_0_OF_pyramidals_48_43_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':43}}
                        
                # For saving to file: pyramidals_48_44.0.dat (ref: pyramidals_48_v_44_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 44; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_44_0_OF_pyramidals_48_44_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':44}}
                        
                # For saving to file: pyramidals_48_45.0.dat (ref: pyramidals_48_v_45_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 45; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_45_0_OF_pyramidals_48_45_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':45}}
                        
                # For saving to file: pyramidals_48_46.0.dat (ref: pyramidals_48_v_46_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 46; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_46_0_OF_pyramidals_48_46_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':46}}
                        
                # For saving to file: pyramidals_48_47.0.dat (ref: pyramidals_48_v_47_0_OF)
                                
        # Column: v: Pop: pyramidals_48; cell: 47; segment id: 0; segment name: soma; Neuron loc: soma(0.5); value: v (v)
        self.simConfig.recordTraces['pyramidals_48_v_47_0_OF_pyramidals_48_47_soma_v'] = {'sec':'soma','loc':0.5,'var':'v','conds':{'pop':'pyramidals_48','cellLabel':47}}
                        
        
        self.simConfig.plotCells = ['all']

        self.simConfig.recordStim = True  # record spikes of cell stims
        self.simConfig.recordStep = self.simConfig.dt # Step size in ms to save data (eg. V traces, LFP, etc)

        # Analysis and plotting, see http://neurosimlab.org/netpyne/reference.html#analysis-related-functions
        self.simConfig.analysis['plotRaster'] = False  # Plot raster
        self.simConfig.analysis['plot2Dnet'] = False  # Plot 2D net cells and connections
        self.simConfig.analysis['plotSpikeHist'] = False # plot spike histogram
        self.simConfig.analysis['plotConn'] = False # plot network connectivity
        self.simConfig.analysis['plotSpikePSD'] = False # plot 3d architecture

        # Saving
        self.simConfig.filename = 'network_ACnet2.txt'  # Set file output name
        self.simConfig.saveFileStep = self.simConfig.dt # step size in ms to save data to disk
        # self.simConfig.saveDat = True # save to dat file
        self.simConfig.saveJson = save_json # save to json file


    def run(self):

        ###############################################################################
        # IMPORT & RUN
        ###############################################################################

        print("Running a NetPyNE based simulation for %sms (dt: %sms) at %s degC"%(self.simConfig.duration, self.simConfig.dt, self.simConfig.hParams['celsius']))

        self.setup_sim_start = time.time()
        self.gids = sim.importNeuroML2SimulateAnalyze(self.nml2_file_name,self.simConfig)

        self.sim_end = time.time()
        self.setup_sim_time = self.sim_end - self.setup_sim_start
        print("Finished NetPyNE simulation in %f seconds (%f mins)..."%(self.setup_sim_time, self.setup_sim_time/60.0))

        try:
            self.save_results()
        except Exception as e:
            print("Exception saving results of NetPyNE simulation: %s" % (e))
            return

    def generate_json_only(self):

          ###############################################################################
          # GENERATE NETPYNE JSON REPRESENTATION OF NETWORK
          ###############################################################################

          print("Generating NetPyNE JSON (and mod files)")

          self.simConfig.saveJson = True # save to json file
          from netpyne.conversion.neuromlFormat import importNeuroML2
          self.gids = sim.importNeuroML2(self.nml2_file_name,
                                         self.simConfig,
                                         simulate=False,
                                         analyze=False)

          from netpyne.sim.save import saveData

          json_filename=__file__.replace(".py","")
          saveData(filename=json_filename, include=["simConfig", "netParams", "net"])
          real_json_filename='%s_data.json'%json_filename

          print("Finished exporting the NetPyNE JSON to %s"%real_json_filename)

          return real_json_filename


    def save_results(self):

        ###############################################################################
        #   Saving data (this ensures the data gets saved in the format/files
        #   as specified in the LEMS <Simulation> element)
        ###############################################################################

        if sim.rank==0:
        
            print("Saving traces to file: baskets_12_0.0.dat (ref: baskets_12_v_0_0_OF)")

                
            # Column: t
            col_baskets_12_v_0_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 0; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_0_0_OF_v = sim.allSimData['baskets_12_v_0_0_OF_baskets_12_0_soma_v']['cell_%s'%self.gids['baskets_12'][0]]
                
            dat_file_baskets_12_v_0_0_OF = open('baskets_12_0.0.dat', 'w')
            for i in range(len(col_baskets_12_v_0_0_OF_t)):
                dat_file_baskets_12_v_0_0_OF.write( '%s\t'%(col_baskets_12_v_0_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_0_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_0_0_OF.close()

        
            print("Saving traces to file: baskets_12_1.0.dat (ref: baskets_12_v_1_0_OF)")

                
            # Column: t
            col_baskets_12_v_1_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 1; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_1_0_OF_v = sim.allSimData['baskets_12_v_1_0_OF_baskets_12_1_soma_v']['cell_%s'%self.gids['baskets_12'][1]]
                
            dat_file_baskets_12_v_1_0_OF = open('baskets_12_1.0.dat', 'w')
            for i in range(len(col_baskets_12_v_1_0_OF_t)):
                dat_file_baskets_12_v_1_0_OF.write( '%s\t'%(col_baskets_12_v_1_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_1_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_1_0_OF.close()

        
            print("Saving traces to file: baskets_12_2.0.dat (ref: baskets_12_v_2_0_OF)")

                
            # Column: t
            col_baskets_12_v_2_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 2; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_2_0_OF_v = sim.allSimData['baskets_12_v_2_0_OF_baskets_12_2_soma_v']['cell_%s'%self.gids['baskets_12'][2]]
                
            dat_file_baskets_12_v_2_0_OF = open('baskets_12_2.0.dat', 'w')
            for i in range(len(col_baskets_12_v_2_0_OF_t)):
                dat_file_baskets_12_v_2_0_OF.write( '%s\t'%(col_baskets_12_v_2_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_2_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_2_0_OF.close()

        
            print("Saving traces to file: baskets_12_3.0.dat (ref: baskets_12_v_3_0_OF)")

                
            # Column: t
            col_baskets_12_v_3_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 3; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_3_0_OF_v = sim.allSimData['baskets_12_v_3_0_OF_baskets_12_3_soma_v']['cell_%s'%self.gids['baskets_12'][3]]
                
            dat_file_baskets_12_v_3_0_OF = open('baskets_12_3.0.dat', 'w')
            for i in range(len(col_baskets_12_v_3_0_OF_t)):
                dat_file_baskets_12_v_3_0_OF.write( '%s\t'%(col_baskets_12_v_3_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_3_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_3_0_OF.close()

        
            print("Saving traces to file: baskets_12_4.0.dat (ref: baskets_12_v_4_0_OF)")

                
            # Column: t
            col_baskets_12_v_4_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 4; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_4_0_OF_v = sim.allSimData['baskets_12_v_4_0_OF_baskets_12_4_soma_v']['cell_%s'%self.gids['baskets_12'][4]]
                
            dat_file_baskets_12_v_4_0_OF = open('baskets_12_4.0.dat', 'w')
            for i in range(len(col_baskets_12_v_4_0_OF_t)):
                dat_file_baskets_12_v_4_0_OF.write( '%s\t'%(col_baskets_12_v_4_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_4_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_4_0_OF.close()

        
            print("Saving traces to file: baskets_12_5.0.dat (ref: baskets_12_v_5_0_OF)")

                
            # Column: t
            col_baskets_12_v_5_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 5; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_5_0_OF_v = sim.allSimData['baskets_12_v_5_0_OF_baskets_12_5_soma_v']['cell_%s'%self.gids['baskets_12'][5]]
                
            dat_file_baskets_12_v_5_0_OF = open('baskets_12_5.0.dat', 'w')
            for i in range(len(col_baskets_12_v_5_0_OF_t)):
                dat_file_baskets_12_v_5_0_OF.write( '%s\t'%(col_baskets_12_v_5_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_5_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_5_0_OF.close()

        
            print("Saving traces to file: baskets_12_6.0.dat (ref: baskets_12_v_6_0_OF)")

                
            # Column: t
            col_baskets_12_v_6_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 6; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_6_0_OF_v = sim.allSimData['baskets_12_v_6_0_OF_baskets_12_6_soma_v']['cell_%s'%self.gids['baskets_12'][6]]
                
            dat_file_baskets_12_v_6_0_OF = open('baskets_12_6.0.dat', 'w')
            for i in range(len(col_baskets_12_v_6_0_OF_t)):
                dat_file_baskets_12_v_6_0_OF.write( '%s\t'%(col_baskets_12_v_6_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_6_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_6_0_OF.close()

        
            print("Saving traces to file: baskets_12_7.0.dat (ref: baskets_12_v_7_0_OF)")

                
            # Column: t
            col_baskets_12_v_7_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 7; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_7_0_OF_v = sim.allSimData['baskets_12_v_7_0_OF_baskets_12_7_soma_v']['cell_%s'%self.gids['baskets_12'][7]]
                
            dat_file_baskets_12_v_7_0_OF = open('baskets_12_7.0.dat', 'w')
            for i in range(len(col_baskets_12_v_7_0_OF_t)):
                dat_file_baskets_12_v_7_0_OF.write( '%s\t'%(col_baskets_12_v_7_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_7_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_7_0_OF.close()

        
            print("Saving traces to file: baskets_12_8.0.dat (ref: baskets_12_v_8_0_OF)")

                
            # Column: t
            col_baskets_12_v_8_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 8; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_8_0_OF_v = sim.allSimData['baskets_12_v_8_0_OF_baskets_12_8_soma_v']['cell_%s'%self.gids['baskets_12'][8]]
                
            dat_file_baskets_12_v_8_0_OF = open('baskets_12_8.0.dat', 'w')
            for i in range(len(col_baskets_12_v_8_0_OF_t)):
                dat_file_baskets_12_v_8_0_OF.write( '%s\t'%(col_baskets_12_v_8_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_8_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_8_0_OF.close()

        
            print("Saving traces to file: baskets_12_9.0.dat (ref: baskets_12_v_9_0_OF)")

                
            # Column: t
            col_baskets_12_v_9_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 9; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_9_0_OF_v = sim.allSimData['baskets_12_v_9_0_OF_baskets_12_9_soma_v']['cell_%s'%self.gids['baskets_12'][9]]
                
            dat_file_baskets_12_v_9_0_OF = open('baskets_12_9.0.dat', 'w')
            for i in range(len(col_baskets_12_v_9_0_OF_t)):
                dat_file_baskets_12_v_9_0_OF.write( '%s\t'%(col_baskets_12_v_9_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_9_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_9_0_OF.close()

        
            print("Saving traces to file: baskets_12_10.0.dat (ref: baskets_12_v_10_0_OF)")

                
            # Column: t
            col_baskets_12_v_10_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 10; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_10_0_OF_v = sim.allSimData['baskets_12_v_10_0_OF_baskets_12_10_soma_v']['cell_%s'%self.gids['baskets_12'][10]]
                
            dat_file_baskets_12_v_10_0_OF = open('baskets_12_10.0.dat', 'w')
            for i in range(len(col_baskets_12_v_10_0_OF_t)):
                dat_file_baskets_12_v_10_0_OF.write( '%s\t'%(col_baskets_12_v_10_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_10_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_10_0_OF.close()

        
            print("Saving traces to file: baskets_12_11.0.dat (ref: baskets_12_v_11_0_OF)")

                
            # Column: t
            col_baskets_12_v_11_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: baskets_12; cell: 11; segment id: 0; segment name: soma; value: v
            col_baskets_12_v_11_0_OF_v = sim.allSimData['baskets_12_v_11_0_OF_baskets_12_11_soma_v']['cell_%s'%self.gids['baskets_12'][11]]
                
            dat_file_baskets_12_v_11_0_OF = open('baskets_12_11.0.dat', 'w')
            for i in range(len(col_baskets_12_v_11_0_OF_t)):
                dat_file_baskets_12_v_11_0_OF.write( '%s\t'%(col_baskets_12_v_11_0_OF_t[i]/1000.0) +  '%s\t'%(col_baskets_12_v_11_0_OF_v[i]/1000.0) +  '\n')
            dat_file_baskets_12_v_11_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_0.0.dat (ref: pyramidals_48_v_0_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_0_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 0; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_0_0_OF_v = sim.allSimData['pyramidals_48_v_0_0_OF_pyramidals_48_0_soma_v']['cell_%s'%self.gids['pyramidals_48'][0]]
                
            dat_file_pyramidals_48_v_0_0_OF = open('pyramidals_48_0.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_0_0_OF_t)):
                dat_file_pyramidals_48_v_0_0_OF.write( '%s\t'%(col_pyramidals_48_v_0_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_0_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_0_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_1.0.dat (ref: pyramidals_48_v_1_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_1_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 1; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_1_0_OF_v = sim.allSimData['pyramidals_48_v_1_0_OF_pyramidals_48_1_soma_v']['cell_%s'%self.gids['pyramidals_48'][1]]
                
            dat_file_pyramidals_48_v_1_0_OF = open('pyramidals_48_1.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_1_0_OF_t)):
                dat_file_pyramidals_48_v_1_0_OF.write( '%s\t'%(col_pyramidals_48_v_1_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_1_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_1_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_2.0.dat (ref: pyramidals_48_v_2_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_2_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 2; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_2_0_OF_v = sim.allSimData['pyramidals_48_v_2_0_OF_pyramidals_48_2_soma_v']['cell_%s'%self.gids['pyramidals_48'][2]]
                
            dat_file_pyramidals_48_v_2_0_OF = open('pyramidals_48_2.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_2_0_OF_t)):
                dat_file_pyramidals_48_v_2_0_OF.write( '%s\t'%(col_pyramidals_48_v_2_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_2_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_2_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_3.0.dat (ref: pyramidals_48_v_3_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_3_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 3; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_3_0_OF_v = sim.allSimData['pyramidals_48_v_3_0_OF_pyramidals_48_3_soma_v']['cell_%s'%self.gids['pyramidals_48'][3]]
                
            dat_file_pyramidals_48_v_3_0_OF = open('pyramidals_48_3.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_3_0_OF_t)):
                dat_file_pyramidals_48_v_3_0_OF.write( '%s\t'%(col_pyramidals_48_v_3_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_3_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_3_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_4.0.dat (ref: pyramidals_48_v_4_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_4_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 4; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_4_0_OF_v = sim.allSimData['pyramidals_48_v_4_0_OF_pyramidals_48_4_soma_v']['cell_%s'%self.gids['pyramidals_48'][4]]
                
            dat_file_pyramidals_48_v_4_0_OF = open('pyramidals_48_4.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_4_0_OF_t)):
                dat_file_pyramidals_48_v_4_0_OF.write( '%s\t'%(col_pyramidals_48_v_4_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_4_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_4_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_5.0.dat (ref: pyramidals_48_v_5_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_5_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 5; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_5_0_OF_v = sim.allSimData['pyramidals_48_v_5_0_OF_pyramidals_48_5_soma_v']['cell_%s'%self.gids['pyramidals_48'][5]]
                
            dat_file_pyramidals_48_v_5_0_OF = open('pyramidals_48_5.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_5_0_OF_t)):
                dat_file_pyramidals_48_v_5_0_OF.write( '%s\t'%(col_pyramidals_48_v_5_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_5_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_5_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_6.0.dat (ref: pyramidals_48_v_6_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_6_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 6; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_6_0_OF_v = sim.allSimData['pyramidals_48_v_6_0_OF_pyramidals_48_6_soma_v']['cell_%s'%self.gids['pyramidals_48'][6]]
                
            dat_file_pyramidals_48_v_6_0_OF = open('pyramidals_48_6.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_6_0_OF_t)):
                dat_file_pyramidals_48_v_6_0_OF.write( '%s\t'%(col_pyramidals_48_v_6_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_6_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_6_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_7.0.dat (ref: pyramidals_48_v_7_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_7_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 7; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_7_0_OF_v = sim.allSimData['pyramidals_48_v_7_0_OF_pyramidals_48_7_soma_v']['cell_%s'%self.gids['pyramidals_48'][7]]
                
            dat_file_pyramidals_48_v_7_0_OF = open('pyramidals_48_7.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_7_0_OF_t)):
                dat_file_pyramidals_48_v_7_0_OF.write( '%s\t'%(col_pyramidals_48_v_7_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_7_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_7_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_8.0.dat (ref: pyramidals_48_v_8_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_8_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 8; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_8_0_OF_v = sim.allSimData['pyramidals_48_v_8_0_OF_pyramidals_48_8_soma_v']['cell_%s'%self.gids['pyramidals_48'][8]]
                
            dat_file_pyramidals_48_v_8_0_OF = open('pyramidals_48_8.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_8_0_OF_t)):
                dat_file_pyramidals_48_v_8_0_OF.write( '%s\t'%(col_pyramidals_48_v_8_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_8_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_8_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_9.0.dat (ref: pyramidals_48_v_9_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_9_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 9; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_9_0_OF_v = sim.allSimData['pyramidals_48_v_9_0_OF_pyramidals_48_9_soma_v']['cell_%s'%self.gids['pyramidals_48'][9]]
                
            dat_file_pyramidals_48_v_9_0_OF = open('pyramidals_48_9.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_9_0_OF_t)):
                dat_file_pyramidals_48_v_9_0_OF.write( '%s\t'%(col_pyramidals_48_v_9_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_9_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_9_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_10.0.dat (ref: pyramidals_48_v_10_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_10_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 10; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_10_0_OF_v = sim.allSimData['pyramidals_48_v_10_0_OF_pyramidals_48_10_soma_v']['cell_%s'%self.gids['pyramidals_48'][10]]
                
            dat_file_pyramidals_48_v_10_0_OF = open('pyramidals_48_10.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_10_0_OF_t)):
                dat_file_pyramidals_48_v_10_0_OF.write( '%s\t'%(col_pyramidals_48_v_10_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_10_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_10_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_11.0.dat (ref: pyramidals_48_v_11_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_11_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 11; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_11_0_OF_v = sim.allSimData['pyramidals_48_v_11_0_OF_pyramidals_48_11_soma_v']['cell_%s'%self.gids['pyramidals_48'][11]]
                
            dat_file_pyramidals_48_v_11_0_OF = open('pyramidals_48_11.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_11_0_OF_t)):
                dat_file_pyramidals_48_v_11_0_OF.write( '%s\t'%(col_pyramidals_48_v_11_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_11_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_11_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_12.0.dat (ref: pyramidals_48_v_12_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_12_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 12; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_12_0_OF_v = sim.allSimData['pyramidals_48_v_12_0_OF_pyramidals_48_12_soma_v']['cell_%s'%self.gids['pyramidals_48'][12]]
                
            dat_file_pyramidals_48_v_12_0_OF = open('pyramidals_48_12.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_12_0_OF_t)):
                dat_file_pyramidals_48_v_12_0_OF.write( '%s\t'%(col_pyramidals_48_v_12_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_12_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_12_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_13.0.dat (ref: pyramidals_48_v_13_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_13_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 13; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_13_0_OF_v = sim.allSimData['pyramidals_48_v_13_0_OF_pyramidals_48_13_soma_v']['cell_%s'%self.gids['pyramidals_48'][13]]
                
            dat_file_pyramidals_48_v_13_0_OF = open('pyramidals_48_13.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_13_0_OF_t)):
                dat_file_pyramidals_48_v_13_0_OF.write( '%s\t'%(col_pyramidals_48_v_13_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_13_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_13_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_14.0.dat (ref: pyramidals_48_v_14_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_14_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 14; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_14_0_OF_v = sim.allSimData['pyramidals_48_v_14_0_OF_pyramidals_48_14_soma_v']['cell_%s'%self.gids['pyramidals_48'][14]]
                
            dat_file_pyramidals_48_v_14_0_OF = open('pyramidals_48_14.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_14_0_OF_t)):
                dat_file_pyramidals_48_v_14_0_OF.write( '%s\t'%(col_pyramidals_48_v_14_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_14_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_14_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_15.0.dat (ref: pyramidals_48_v_15_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_15_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 15; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_15_0_OF_v = sim.allSimData['pyramidals_48_v_15_0_OF_pyramidals_48_15_soma_v']['cell_%s'%self.gids['pyramidals_48'][15]]
                
            dat_file_pyramidals_48_v_15_0_OF = open('pyramidals_48_15.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_15_0_OF_t)):
                dat_file_pyramidals_48_v_15_0_OF.write( '%s\t'%(col_pyramidals_48_v_15_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_15_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_15_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_16.0.dat (ref: pyramidals_48_v_16_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_16_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 16; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_16_0_OF_v = sim.allSimData['pyramidals_48_v_16_0_OF_pyramidals_48_16_soma_v']['cell_%s'%self.gids['pyramidals_48'][16]]
                
            dat_file_pyramidals_48_v_16_0_OF = open('pyramidals_48_16.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_16_0_OF_t)):
                dat_file_pyramidals_48_v_16_0_OF.write( '%s\t'%(col_pyramidals_48_v_16_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_16_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_16_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_17.0.dat (ref: pyramidals_48_v_17_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_17_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 17; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_17_0_OF_v = sim.allSimData['pyramidals_48_v_17_0_OF_pyramidals_48_17_soma_v']['cell_%s'%self.gids['pyramidals_48'][17]]
                
            dat_file_pyramidals_48_v_17_0_OF = open('pyramidals_48_17.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_17_0_OF_t)):
                dat_file_pyramidals_48_v_17_0_OF.write( '%s\t'%(col_pyramidals_48_v_17_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_17_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_17_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_18.0.dat (ref: pyramidals_48_v_18_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_18_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 18; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_18_0_OF_v = sim.allSimData['pyramidals_48_v_18_0_OF_pyramidals_48_18_soma_v']['cell_%s'%self.gids['pyramidals_48'][18]]
                
            dat_file_pyramidals_48_v_18_0_OF = open('pyramidals_48_18.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_18_0_OF_t)):
                dat_file_pyramidals_48_v_18_0_OF.write( '%s\t'%(col_pyramidals_48_v_18_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_18_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_18_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_19.0.dat (ref: pyramidals_48_v_19_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_19_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 19; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_19_0_OF_v = sim.allSimData['pyramidals_48_v_19_0_OF_pyramidals_48_19_soma_v']['cell_%s'%self.gids['pyramidals_48'][19]]
                
            dat_file_pyramidals_48_v_19_0_OF = open('pyramidals_48_19.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_19_0_OF_t)):
                dat_file_pyramidals_48_v_19_0_OF.write( '%s\t'%(col_pyramidals_48_v_19_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_19_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_19_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_20.0.dat (ref: pyramidals_48_v_20_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_20_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 20; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_20_0_OF_v = sim.allSimData['pyramidals_48_v_20_0_OF_pyramidals_48_20_soma_v']['cell_%s'%self.gids['pyramidals_48'][20]]
                
            dat_file_pyramidals_48_v_20_0_OF = open('pyramidals_48_20.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_20_0_OF_t)):
                dat_file_pyramidals_48_v_20_0_OF.write( '%s\t'%(col_pyramidals_48_v_20_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_20_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_20_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_21.0.dat (ref: pyramidals_48_v_21_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_21_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 21; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_21_0_OF_v = sim.allSimData['pyramidals_48_v_21_0_OF_pyramidals_48_21_soma_v']['cell_%s'%self.gids['pyramidals_48'][21]]
                
            dat_file_pyramidals_48_v_21_0_OF = open('pyramidals_48_21.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_21_0_OF_t)):
                dat_file_pyramidals_48_v_21_0_OF.write( '%s\t'%(col_pyramidals_48_v_21_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_21_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_21_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_22.0.dat (ref: pyramidals_48_v_22_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_22_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 22; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_22_0_OF_v = sim.allSimData['pyramidals_48_v_22_0_OF_pyramidals_48_22_soma_v']['cell_%s'%self.gids['pyramidals_48'][22]]
                
            dat_file_pyramidals_48_v_22_0_OF = open('pyramidals_48_22.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_22_0_OF_t)):
                dat_file_pyramidals_48_v_22_0_OF.write( '%s\t'%(col_pyramidals_48_v_22_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_22_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_22_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_23.0.dat (ref: pyramidals_48_v_23_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_23_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 23; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_23_0_OF_v = sim.allSimData['pyramidals_48_v_23_0_OF_pyramidals_48_23_soma_v']['cell_%s'%self.gids['pyramidals_48'][23]]
                
            dat_file_pyramidals_48_v_23_0_OF = open('pyramidals_48_23.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_23_0_OF_t)):
                dat_file_pyramidals_48_v_23_0_OF.write( '%s\t'%(col_pyramidals_48_v_23_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_23_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_23_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_24.0.dat (ref: pyramidals_48_v_24_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_24_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 24; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_24_0_OF_v = sim.allSimData['pyramidals_48_v_24_0_OF_pyramidals_48_24_soma_v']['cell_%s'%self.gids['pyramidals_48'][24]]
                
            dat_file_pyramidals_48_v_24_0_OF = open('pyramidals_48_24.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_24_0_OF_t)):
                dat_file_pyramidals_48_v_24_0_OF.write( '%s\t'%(col_pyramidals_48_v_24_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_24_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_24_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_25.0.dat (ref: pyramidals_48_v_25_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_25_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 25; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_25_0_OF_v = sim.allSimData['pyramidals_48_v_25_0_OF_pyramidals_48_25_soma_v']['cell_%s'%self.gids['pyramidals_48'][25]]
                
            dat_file_pyramidals_48_v_25_0_OF = open('pyramidals_48_25.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_25_0_OF_t)):
                dat_file_pyramidals_48_v_25_0_OF.write( '%s\t'%(col_pyramidals_48_v_25_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_25_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_25_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_26.0.dat (ref: pyramidals_48_v_26_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_26_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 26; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_26_0_OF_v = sim.allSimData['pyramidals_48_v_26_0_OF_pyramidals_48_26_soma_v']['cell_%s'%self.gids['pyramidals_48'][26]]
                
            dat_file_pyramidals_48_v_26_0_OF = open('pyramidals_48_26.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_26_0_OF_t)):
                dat_file_pyramidals_48_v_26_0_OF.write( '%s\t'%(col_pyramidals_48_v_26_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_26_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_26_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_27.0.dat (ref: pyramidals_48_v_27_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_27_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 27; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_27_0_OF_v = sim.allSimData['pyramidals_48_v_27_0_OF_pyramidals_48_27_soma_v']['cell_%s'%self.gids['pyramidals_48'][27]]
                
            dat_file_pyramidals_48_v_27_0_OF = open('pyramidals_48_27.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_27_0_OF_t)):
                dat_file_pyramidals_48_v_27_0_OF.write( '%s\t'%(col_pyramidals_48_v_27_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_27_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_27_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_28.0.dat (ref: pyramidals_48_v_28_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_28_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 28; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_28_0_OF_v = sim.allSimData['pyramidals_48_v_28_0_OF_pyramidals_48_28_soma_v']['cell_%s'%self.gids['pyramidals_48'][28]]
                
            dat_file_pyramidals_48_v_28_0_OF = open('pyramidals_48_28.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_28_0_OF_t)):
                dat_file_pyramidals_48_v_28_0_OF.write( '%s\t'%(col_pyramidals_48_v_28_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_28_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_28_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_29.0.dat (ref: pyramidals_48_v_29_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_29_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 29; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_29_0_OF_v = sim.allSimData['pyramidals_48_v_29_0_OF_pyramidals_48_29_soma_v']['cell_%s'%self.gids['pyramidals_48'][29]]
                
            dat_file_pyramidals_48_v_29_0_OF = open('pyramidals_48_29.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_29_0_OF_t)):
                dat_file_pyramidals_48_v_29_0_OF.write( '%s\t'%(col_pyramidals_48_v_29_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_29_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_29_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_30.0.dat (ref: pyramidals_48_v_30_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_30_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 30; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_30_0_OF_v = sim.allSimData['pyramidals_48_v_30_0_OF_pyramidals_48_30_soma_v']['cell_%s'%self.gids['pyramidals_48'][30]]
                
            dat_file_pyramidals_48_v_30_0_OF = open('pyramidals_48_30.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_30_0_OF_t)):
                dat_file_pyramidals_48_v_30_0_OF.write( '%s\t'%(col_pyramidals_48_v_30_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_30_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_30_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_31.0.dat (ref: pyramidals_48_v_31_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_31_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 31; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_31_0_OF_v = sim.allSimData['pyramidals_48_v_31_0_OF_pyramidals_48_31_soma_v']['cell_%s'%self.gids['pyramidals_48'][31]]
                
            dat_file_pyramidals_48_v_31_0_OF = open('pyramidals_48_31.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_31_0_OF_t)):
                dat_file_pyramidals_48_v_31_0_OF.write( '%s\t'%(col_pyramidals_48_v_31_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_31_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_31_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_32.0.dat (ref: pyramidals_48_v_32_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_32_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 32; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_32_0_OF_v = sim.allSimData['pyramidals_48_v_32_0_OF_pyramidals_48_32_soma_v']['cell_%s'%self.gids['pyramidals_48'][32]]
                
            dat_file_pyramidals_48_v_32_0_OF = open('pyramidals_48_32.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_32_0_OF_t)):
                dat_file_pyramidals_48_v_32_0_OF.write( '%s\t'%(col_pyramidals_48_v_32_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_32_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_32_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_33.0.dat (ref: pyramidals_48_v_33_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_33_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 33; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_33_0_OF_v = sim.allSimData['pyramidals_48_v_33_0_OF_pyramidals_48_33_soma_v']['cell_%s'%self.gids['pyramidals_48'][33]]
                
            dat_file_pyramidals_48_v_33_0_OF = open('pyramidals_48_33.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_33_0_OF_t)):
                dat_file_pyramidals_48_v_33_0_OF.write( '%s\t'%(col_pyramidals_48_v_33_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_33_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_33_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_34.0.dat (ref: pyramidals_48_v_34_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_34_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 34; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_34_0_OF_v = sim.allSimData['pyramidals_48_v_34_0_OF_pyramidals_48_34_soma_v']['cell_%s'%self.gids['pyramidals_48'][34]]
                
            dat_file_pyramidals_48_v_34_0_OF = open('pyramidals_48_34.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_34_0_OF_t)):
                dat_file_pyramidals_48_v_34_0_OF.write( '%s\t'%(col_pyramidals_48_v_34_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_34_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_34_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_35.0.dat (ref: pyramidals_48_v_35_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_35_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 35; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_35_0_OF_v = sim.allSimData['pyramidals_48_v_35_0_OF_pyramidals_48_35_soma_v']['cell_%s'%self.gids['pyramidals_48'][35]]
                
            dat_file_pyramidals_48_v_35_0_OF = open('pyramidals_48_35.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_35_0_OF_t)):
                dat_file_pyramidals_48_v_35_0_OF.write( '%s\t'%(col_pyramidals_48_v_35_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_35_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_35_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_36.0.dat (ref: pyramidals_48_v_36_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_36_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 36; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_36_0_OF_v = sim.allSimData['pyramidals_48_v_36_0_OF_pyramidals_48_36_soma_v']['cell_%s'%self.gids['pyramidals_48'][36]]
                
            dat_file_pyramidals_48_v_36_0_OF = open('pyramidals_48_36.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_36_0_OF_t)):
                dat_file_pyramidals_48_v_36_0_OF.write( '%s\t'%(col_pyramidals_48_v_36_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_36_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_36_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_37.0.dat (ref: pyramidals_48_v_37_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_37_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 37; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_37_0_OF_v = sim.allSimData['pyramidals_48_v_37_0_OF_pyramidals_48_37_soma_v']['cell_%s'%self.gids['pyramidals_48'][37]]
                
            dat_file_pyramidals_48_v_37_0_OF = open('pyramidals_48_37.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_37_0_OF_t)):
                dat_file_pyramidals_48_v_37_0_OF.write( '%s\t'%(col_pyramidals_48_v_37_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_37_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_37_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_38.0.dat (ref: pyramidals_48_v_38_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_38_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 38; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_38_0_OF_v = sim.allSimData['pyramidals_48_v_38_0_OF_pyramidals_48_38_soma_v']['cell_%s'%self.gids['pyramidals_48'][38]]
                
            dat_file_pyramidals_48_v_38_0_OF = open('pyramidals_48_38.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_38_0_OF_t)):
                dat_file_pyramidals_48_v_38_0_OF.write( '%s\t'%(col_pyramidals_48_v_38_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_38_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_38_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_39.0.dat (ref: pyramidals_48_v_39_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_39_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 39; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_39_0_OF_v = sim.allSimData['pyramidals_48_v_39_0_OF_pyramidals_48_39_soma_v']['cell_%s'%self.gids['pyramidals_48'][39]]
                
            dat_file_pyramidals_48_v_39_0_OF = open('pyramidals_48_39.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_39_0_OF_t)):
                dat_file_pyramidals_48_v_39_0_OF.write( '%s\t'%(col_pyramidals_48_v_39_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_39_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_39_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_40.0.dat (ref: pyramidals_48_v_40_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_40_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 40; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_40_0_OF_v = sim.allSimData['pyramidals_48_v_40_0_OF_pyramidals_48_40_soma_v']['cell_%s'%self.gids['pyramidals_48'][40]]
                
            dat_file_pyramidals_48_v_40_0_OF = open('pyramidals_48_40.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_40_0_OF_t)):
                dat_file_pyramidals_48_v_40_0_OF.write( '%s\t'%(col_pyramidals_48_v_40_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_40_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_40_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_41.0.dat (ref: pyramidals_48_v_41_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_41_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 41; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_41_0_OF_v = sim.allSimData['pyramidals_48_v_41_0_OF_pyramidals_48_41_soma_v']['cell_%s'%self.gids['pyramidals_48'][41]]
                
            dat_file_pyramidals_48_v_41_0_OF = open('pyramidals_48_41.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_41_0_OF_t)):
                dat_file_pyramidals_48_v_41_0_OF.write( '%s\t'%(col_pyramidals_48_v_41_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_41_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_41_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_42.0.dat (ref: pyramidals_48_v_42_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_42_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 42; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_42_0_OF_v = sim.allSimData['pyramidals_48_v_42_0_OF_pyramidals_48_42_soma_v']['cell_%s'%self.gids['pyramidals_48'][42]]
                
            dat_file_pyramidals_48_v_42_0_OF = open('pyramidals_48_42.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_42_0_OF_t)):
                dat_file_pyramidals_48_v_42_0_OF.write( '%s\t'%(col_pyramidals_48_v_42_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_42_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_42_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_43.0.dat (ref: pyramidals_48_v_43_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_43_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 43; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_43_0_OF_v = sim.allSimData['pyramidals_48_v_43_0_OF_pyramidals_48_43_soma_v']['cell_%s'%self.gids['pyramidals_48'][43]]
                
            dat_file_pyramidals_48_v_43_0_OF = open('pyramidals_48_43.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_43_0_OF_t)):
                dat_file_pyramidals_48_v_43_0_OF.write( '%s\t'%(col_pyramidals_48_v_43_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_43_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_43_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_44.0.dat (ref: pyramidals_48_v_44_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_44_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 44; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_44_0_OF_v = sim.allSimData['pyramidals_48_v_44_0_OF_pyramidals_48_44_soma_v']['cell_%s'%self.gids['pyramidals_48'][44]]
                
            dat_file_pyramidals_48_v_44_0_OF = open('pyramidals_48_44.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_44_0_OF_t)):
                dat_file_pyramidals_48_v_44_0_OF.write( '%s\t'%(col_pyramidals_48_v_44_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_44_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_44_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_45.0.dat (ref: pyramidals_48_v_45_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_45_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 45; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_45_0_OF_v = sim.allSimData['pyramidals_48_v_45_0_OF_pyramidals_48_45_soma_v']['cell_%s'%self.gids['pyramidals_48'][45]]
                
            dat_file_pyramidals_48_v_45_0_OF = open('pyramidals_48_45.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_45_0_OF_t)):
                dat_file_pyramidals_48_v_45_0_OF.write( '%s\t'%(col_pyramidals_48_v_45_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_45_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_45_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_46.0.dat (ref: pyramidals_48_v_46_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_46_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 46; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_46_0_OF_v = sim.allSimData['pyramidals_48_v_46_0_OF_pyramidals_48_46_soma_v']['cell_%s'%self.gids['pyramidals_48'][46]]
                
            dat_file_pyramidals_48_v_46_0_OF = open('pyramidals_48_46.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_46_0_OF_t)):
                dat_file_pyramidals_48_v_46_0_OF.write( '%s\t'%(col_pyramidals_48_v_46_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_46_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_46_0_OF.close()

        
            print("Saving traces to file: pyramidals_48_47.0.dat (ref: pyramidals_48_v_47_0_OF)")

                
            # Column: t
            col_pyramidals_48_v_47_0_OF_t = [i*self.simConfig.dt for i in range(int(self.simConfig.duration/self.simConfig.dt))]
                        
            # Column: v: Pop: pyramidals_48; cell: 47; segment id: 0; segment name: soma; value: v
            col_pyramidals_48_v_47_0_OF_v = sim.allSimData['pyramidals_48_v_47_0_OF_pyramidals_48_47_soma_v']['cell_%s'%self.gids['pyramidals_48'][47]]
                
            dat_file_pyramidals_48_v_47_0_OF = open('pyramidals_48_47.0.dat', 'w')
            for i in range(len(col_pyramidals_48_v_47_0_OF_t)):
                dat_file_pyramidals_48_v_47_0_OF.write( '%s\t'%(col_pyramidals_48_v_47_0_OF_t[i]/1000.0) +  '%s\t'%(col_pyramidals_48_v_47_0_OF_v[i]/1000.0) +  '\n')
            dat_file_pyramidals_48_v_47_0_OF.close()

        
        
            save_end = time.time()
            save_time = save_end - self.sim_end
            print("Finished saving results in %f seconds"%(save_time))


        
            self.report_file = open('simulator.props','a')
            self.report_file.write('StartTime=%s\n'%datetime.datetime.fromtimestamp(self.setup_start).strftime('%Y-%m-%d %H:%M:%S'))
            self.report_file.write('RealSetupAndSimulationTime=%s\n'%self.setup_sim_time)
            self.report_file.write('SimulationSaveTime=%s\n'%save_time)
            self.report_file.close()
            print("Saving report of simulation to %s"%('simulator.props'))
        
if __name__ == '__main__':

    save_json = '-json' in sys.argv
    no_run = '-norun' in sys.argv

    ns = NetPyNESimulation(tstop=500.0, dt=0.01, seed=123456789, save_json=save_json, abs_tol=None)

    if not no_run:
      ns.run()
    else:
      if save_json:
        fn = ns.generate_json_only()
        print("Generated: %s"%fn)
        quit()

    if '-nogui' in sys.argv:
        quit()
